################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Each subdirectory must supply rules for building sources it contributes
source/F28M36x_Adc.obj: /home/gabriel/LNLS/DRS/Firmware/C28/F28M36x_common/source/F28M36x_Adc.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C2000 Compiler'
	"/home/gabriel/ti/ccsv6/tools/compiler/ti-cgt-c2000_15.12.1.LTS/bin/cl2000" -v28 -ml -mt --float_support=fpu32 --vcu_support=vcu0 -O2 --opt_for_speed=1 --include_path="/home/gabriel/LNLS/DRS/Firmware/C28/F28M36x_ELP_DRS" --include_path="/home/gabriel/LNLS/DRS/Firmware/C28/F28M36x_ELP_DRS/DP_framework" --include_path="/home/gabriel/LNLS/DRS/Firmware/C28/F28M36x_ELP_DRS/DP_framework/ELP_DCL" --include_path="/home/gabriel/LNLS/DRS/Firmware/C28/F28M36x_ELP_DRS/DP_framework/SigGen" --include_path="/home/gabriel/LNLS/DRS/Firmware/C28/F28M36x_ELP_DRS/DP_framework/TimeSlicer" --include_path="/home/gabriel/LNLS/DRS/Firmware/C28/F28M36x_ELP_DRS/DP_framework/TI_DCL" --include_path="/home/gabriel/LNLS/DRS/Firmware/C28/F28M36x_ELP_DRS/HRADC_board" --include_path="/home/gabriel/LNLS/DRS/Firmware/C28/F28M36x_ELP_DRS/IPC_modules" --include_path="/home/gabriel/LNLS/DRS/Firmware/C28/F28M36x_ELP_DRS/PS_modules" --include_path="/home/gabriel/LNLS/DRS/Firmware/C28/F28M36x_ELP_DRS/PWM_modules" --include_path="/home/gabriel/ti/ccsv6/tools/compiler/ti-cgt-c2000_15.12.1.LTS/include" --include_path="/home/gabriel/LNLS/DRS/Firmware/C28/F28M36x_common/include" --include_path="/home/gabriel/LNLS/DRS/Firmware/C28/F28M36x_headers/include" -g --diag_warning=225 --display_error_number --issue_remarks --diag_wrap=off --preproc_with_compile --preproc_dependency="source/F28M36x_Adc.d" --obj_directory="source" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: $<'
	@echo ' '

source/F28M36x_CodeStartBranch.obj: /home/gabriel/LNLS/DRS/Firmware/C28/F28M36x_common/source/F28M36x_CodeStartBranch.asm $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C2000 Compiler'
	"/home/gabriel/ti/ccsv6/tools/compiler/ti-cgt-c2000_15.12.1.LTS/bin/cl2000" -v28 -ml -mt --float_support=fpu32 --vcu_support=vcu0 -O2 --opt_for_speed=1 --include_path="/home/gabriel/LNLS/DRS/Firmware/C28/F28M36x_ELP_DRS" --include_path="/home/gabriel/LNLS/DRS/Firmware/C28/F28M36x_ELP_DRS/DP_framework" --include_path="/home/gabriel/LNLS/DRS/Firmware/C28/F28M36x_ELP_DRS/DP_framework/ELP_DCL" --include_path="/home/gabriel/LNLS/DRS/Firmware/C28/F28M36x_ELP_DRS/DP_framework/SigGen" --include_path="/home/gabriel/LNLS/DRS/Firmware/C28/F28M36x_ELP_DRS/DP_framework/TimeSlicer" --include_path="/home/gabriel/LNLS/DRS/Firmware/C28/F28M36x_ELP_DRS/DP_framework/TI_DCL" --include_path="/home/gabriel/LNLS/DRS/Firmware/C28/F28M36x_ELP_DRS/HRADC_board" --include_path="/home/gabriel/LNLS/DRS/Firmware/C28/F28M36x_ELP_DRS/IPC_modules" --include_path="/home/gabriel/LNLS/DRS/Firmware/C28/F28M36x_ELP_DRS/PS_modules" --include_path="/home/gabriel/LNLS/DRS/Firmware/C28/F28M36x_ELP_DRS/PWM_modules" --include_path="/home/gabriel/ti/ccsv6/tools/compiler/ti-cgt-c2000_15.12.1.LTS/include" --include_path="/home/gabriel/LNLS/DRS/Firmware/C28/F28M36x_common/include" --include_path="/home/gabriel/LNLS/DRS/Firmware/C28/F28M36x_headers/include" -g --diag_warning=225 --display_error_number --issue_remarks --diag_wrap=off --preproc_with_compile --preproc_dependency="source/F28M36x_CodeStartBranch.d" --obj_directory="source" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: $<'
	@echo ' '

source/F28M36x_Comp.obj: /home/gabriel/LNLS/DRS/Firmware/C28/F28M36x_common/source/F28M36x_Comp.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C2000 Compiler'
	"/home/gabriel/ti/ccsv6/tools/compiler/ti-cgt-c2000_15.12.1.LTS/bin/cl2000" -v28 -ml -mt --float_support=fpu32 --vcu_support=vcu0 -O2 --opt_for_speed=1 --include_path="/home/gabriel/LNLS/DRS/Firmware/C28/F28M36x_ELP_DRS" --include_path="/home/gabriel/LNLS/DRS/Firmware/C28/F28M36x_ELP_DRS/DP_framework" --include_path="/home/gabriel/LNLS/DRS/Firmware/C28/F28M36x_ELP_DRS/DP_framework/ELP_DCL" --include_path="/home/gabriel/LNLS/DRS/Firmware/C28/F28M36x_ELP_DRS/DP_framework/SigGen" --include_path="/home/gabriel/LNLS/DRS/Firmware/C28/F28M36x_ELP_DRS/DP_framework/TimeSlicer" --include_path="/home/gabriel/LNLS/DRS/Firmware/C28/F28M36x_ELP_DRS/DP_framework/TI_DCL" --include_path="/home/gabriel/LNLS/DRS/Firmware/C28/F28M36x_ELP_DRS/HRADC_board" --include_path="/home/gabriel/LNLS/DRS/Firmware/C28/F28M36x_ELP_DRS/IPC_modules" --include_path="/home/gabriel/LNLS/DRS/Firmware/C28/F28M36x_ELP_DRS/PS_modules" --include_path="/home/gabriel/LNLS/DRS/Firmware/C28/F28M36x_ELP_DRS/PWM_modules" --include_path="/home/gabriel/ti/ccsv6/tools/compiler/ti-cgt-c2000_15.12.1.LTS/include" --include_path="/home/gabriel/LNLS/DRS/Firmware/C28/F28M36x_common/include" --include_path="/home/gabriel/LNLS/DRS/Firmware/C28/F28M36x_headers/include" -g --diag_warning=225 --display_error_number --issue_remarks --diag_wrap=off --preproc_with_compile --preproc_dependency="source/F28M36x_Comp.d" --obj_directory="source" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: $<'
	@echo ' '

source/F28M36x_CpuTimers.obj: /home/gabriel/LNLS/DRS/Firmware/C28/F28M36x_common/source/F28M36x_CpuTimers.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C2000 Compiler'
	"/home/gabriel/ti/ccsv6/tools/compiler/ti-cgt-c2000_15.12.1.LTS/bin/cl2000" -v28 -ml -mt --float_support=fpu32 --vcu_support=vcu0 -O2 --opt_for_speed=1 --include_path="/home/gabriel/LNLS/DRS/Firmware/C28/F28M36x_ELP_DRS" --include_path="/home/gabriel/LNLS/DRS/Firmware/C28/F28M36x_ELP_DRS/DP_framework" --include_path="/home/gabriel/LNLS/DRS/Firmware/C28/F28M36x_ELP_DRS/DP_framework/ELP_DCL" --include_path="/home/gabriel/LNLS/DRS/Firmware/C28/F28M36x_ELP_DRS/DP_framework/SigGen" --include_path="/home/gabriel/LNLS/DRS/Firmware/C28/F28M36x_ELP_DRS/DP_framework/TimeSlicer" --include_path="/home/gabriel/LNLS/DRS/Firmware/C28/F28M36x_ELP_DRS/DP_framework/TI_DCL" --include_path="/home/gabriel/LNLS/DRS/Firmware/C28/F28M36x_ELP_DRS/HRADC_board" --include_path="/home/gabriel/LNLS/DRS/Firmware/C28/F28M36x_ELP_DRS/IPC_modules" --include_path="/home/gabriel/LNLS/DRS/Firmware/C28/F28M36x_ELP_DRS/PS_modules" --include_path="/home/gabriel/LNLS/DRS/Firmware/C28/F28M36x_ELP_DRS/PWM_modules" --include_path="/home/gabriel/ti/ccsv6/tools/compiler/ti-cgt-c2000_15.12.1.LTS/include" --include_path="/home/gabriel/LNLS/DRS/Firmware/C28/F28M36x_common/include" --include_path="/home/gabriel/LNLS/DRS/Firmware/C28/F28M36x_headers/include" -g --diag_warning=225 --display_error_number --issue_remarks --diag_wrap=off --preproc_with_compile --preproc_dependency="source/F28M36x_CpuTimers.d" --obj_directory="source" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: $<'
	@echo ' '

source/F28M36x_DMA.obj: /home/gabriel/LNLS/DRS/Firmware/C28/F28M36x_common/source/F28M36x_DMA.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C2000 Compiler'
	"/home/gabriel/ti/ccsv6/tools/compiler/ti-cgt-c2000_15.12.1.LTS/bin/cl2000" -v28 -ml -mt --float_support=fpu32 --vcu_support=vcu0 -O2 --opt_for_speed=1 --include_path="/home/gabriel/LNLS/DRS/Firmware/C28/F28M36x_ELP_DRS" --include_path="/home/gabriel/LNLS/DRS/Firmware/C28/F28M36x_ELP_DRS/DP_framework" --include_path="/home/gabriel/LNLS/DRS/Firmware/C28/F28M36x_ELP_DRS/DP_framework/ELP_DCL" --include_path="/home/gabriel/LNLS/DRS/Firmware/C28/F28M36x_ELP_DRS/DP_framework/SigGen" --include_path="/home/gabriel/LNLS/DRS/Firmware/C28/F28M36x_ELP_DRS/DP_framework/TimeSlicer" --include_path="/home/gabriel/LNLS/DRS/Firmware/C28/F28M36x_ELP_DRS/DP_framework/TI_DCL" --include_path="/home/gabriel/LNLS/DRS/Firmware/C28/F28M36x_ELP_DRS/HRADC_board" --include_path="/home/gabriel/LNLS/DRS/Firmware/C28/F28M36x_ELP_DRS/IPC_modules" --include_path="/home/gabriel/LNLS/DRS/Firmware/C28/F28M36x_ELP_DRS/PS_modules" --include_path="/home/gabriel/LNLS/DRS/Firmware/C28/F28M36x_ELP_DRS/PWM_modules" --include_path="/home/gabriel/ti/ccsv6/tools/compiler/ti-cgt-c2000_15.12.1.LTS/include" --include_path="/home/gabriel/LNLS/DRS/Firmware/C28/F28M36x_common/include" --include_path="/home/gabriel/LNLS/DRS/Firmware/C28/F28M36x_headers/include" -g --diag_warning=225 --display_error_number --issue_remarks --diag_wrap=off --preproc_with_compile --preproc_dependency="source/F28M36x_DMA.d" --obj_directory="source" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: $<'
	@echo ' '

source/F28M36x_DefaultIsr.obj: /home/gabriel/LNLS/DRS/Firmware/C28/F28M36x_common/source/F28M36x_DefaultIsr.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C2000 Compiler'
	"/home/gabriel/ti/ccsv6/tools/compiler/ti-cgt-c2000_15.12.1.LTS/bin/cl2000" -v28 -ml -mt --float_support=fpu32 --vcu_support=vcu0 -O2 --opt_for_speed=1 --include_path="/home/gabriel/LNLS/DRS/Firmware/C28/F28M36x_ELP_DRS" --include_path="/home/gabriel/LNLS/DRS/Firmware/C28/F28M36x_ELP_DRS/DP_framework" --include_path="/home/gabriel/LNLS/DRS/Firmware/C28/F28M36x_ELP_DRS/DP_framework/ELP_DCL" --include_path="/home/gabriel/LNLS/DRS/Firmware/C28/F28M36x_ELP_DRS/DP_framework/SigGen" --include_path="/home/gabriel/LNLS/DRS/Firmware/C28/F28M36x_ELP_DRS/DP_framework/TimeSlicer" --include_path="/home/gabriel/LNLS/DRS/Firmware/C28/F28M36x_ELP_DRS/DP_framework/TI_DCL" --include_path="/home/gabriel/LNLS/DRS/Firmware/C28/F28M36x_ELP_DRS/HRADC_board" --include_path="/home/gabriel/LNLS/DRS/Firmware/C28/F28M36x_ELP_DRS/IPC_modules" --include_path="/home/gabriel/LNLS/DRS/Firmware/C28/F28M36x_ELP_DRS/PS_modules" --include_path="/home/gabriel/LNLS/DRS/Firmware/C28/F28M36x_ELP_DRS/PWM_modules" --include_path="/home/gabriel/ti/ccsv6/tools/compiler/ti-cgt-c2000_15.12.1.LTS/include" --include_path="/home/gabriel/LNLS/DRS/Firmware/C28/F28M36x_common/include" --include_path="/home/gabriel/LNLS/DRS/Firmware/C28/F28M36x_headers/include" -g --diag_warning=225 --display_error_number --issue_remarks --diag_wrap=off --preproc_with_compile --preproc_dependency="source/F28M36x_DefaultIsr.d" --obj_directory="source" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: $<'
	@echo ' '

source/F28M36x_EPwm.obj: /home/gabriel/LNLS/DRS/Firmware/C28/F28M36x_common/source/F28M36x_EPwm.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C2000 Compiler'
	"/home/gabriel/ti/ccsv6/tools/compiler/ti-cgt-c2000_15.12.1.LTS/bin/cl2000" -v28 -ml -mt --float_support=fpu32 --vcu_support=vcu0 -O2 --opt_for_speed=1 --include_path="/home/gabriel/LNLS/DRS/Firmware/C28/F28M36x_ELP_DRS" --include_path="/home/gabriel/LNLS/DRS/Firmware/C28/F28M36x_ELP_DRS/DP_framework" --include_path="/home/gabriel/LNLS/DRS/Firmware/C28/F28M36x_ELP_DRS/DP_framework/ELP_DCL" --include_path="/home/gabriel/LNLS/DRS/Firmware/C28/F28M36x_ELP_DRS/DP_framework/SigGen" --include_path="/home/gabriel/LNLS/DRS/Firmware/C28/F28M36x_ELP_DRS/DP_framework/TimeSlicer" --include_path="/home/gabriel/LNLS/DRS/Firmware/C28/F28M36x_ELP_DRS/DP_framework/TI_DCL" --include_path="/home/gabriel/LNLS/DRS/Firmware/C28/F28M36x_ELP_DRS/HRADC_board" --include_path="/home/gabriel/LNLS/DRS/Firmware/C28/F28M36x_ELP_DRS/IPC_modules" --include_path="/home/gabriel/LNLS/DRS/Firmware/C28/F28M36x_ELP_DRS/PS_modules" --include_path="/home/gabriel/LNLS/DRS/Firmware/C28/F28M36x_ELP_DRS/PWM_modules" --include_path="/home/gabriel/ti/ccsv6/tools/compiler/ti-cgt-c2000_15.12.1.LTS/include" --include_path="/home/gabriel/LNLS/DRS/Firmware/C28/F28M36x_common/include" --include_path="/home/gabriel/LNLS/DRS/Firmware/C28/F28M36x_headers/include" -g --diag_warning=225 --display_error_number --issue_remarks --diag_wrap=off --preproc_with_compile --preproc_dependency="source/F28M36x_EPwm.d" --obj_directory="source" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: $<'
	@echo ' '

source/F28M36x_Gpio.obj: /home/gabriel/LNLS/DRS/Firmware/C28/F28M36x_common/source/F28M36x_Gpio.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C2000 Compiler'
	"/home/gabriel/ti/ccsv6/tools/compiler/ti-cgt-c2000_15.12.1.LTS/bin/cl2000" -v28 -ml -mt --float_support=fpu32 --vcu_support=vcu0 -O2 --opt_for_speed=1 --include_path="/home/gabriel/LNLS/DRS/Firmware/C28/F28M36x_ELP_DRS" --include_path="/home/gabriel/LNLS/DRS/Firmware/C28/F28M36x_ELP_DRS/DP_framework" --include_path="/home/gabriel/LNLS/DRS/Firmware/C28/F28M36x_ELP_DRS/DP_framework/ELP_DCL" --include_path="/home/gabriel/LNLS/DRS/Firmware/C28/F28M36x_ELP_DRS/DP_framework/SigGen" --include_path="/home/gabriel/LNLS/DRS/Firmware/C28/F28M36x_ELP_DRS/DP_framework/TimeSlicer" --include_path="/home/gabriel/LNLS/DRS/Firmware/C28/F28M36x_ELP_DRS/DP_framework/TI_DCL" --include_path="/home/gabriel/LNLS/DRS/Firmware/C28/F28M36x_ELP_DRS/HRADC_board" --include_path="/home/gabriel/LNLS/DRS/Firmware/C28/F28M36x_ELP_DRS/IPC_modules" --include_path="/home/gabriel/LNLS/DRS/Firmware/C28/F28M36x_ELP_DRS/PS_modules" --include_path="/home/gabriel/LNLS/DRS/Firmware/C28/F28M36x_ELP_DRS/PWM_modules" --include_path="/home/gabriel/ti/ccsv6/tools/compiler/ti-cgt-c2000_15.12.1.LTS/include" --include_path="/home/gabriel/LNLS/DRS/Firmware/C28/F28M36x_common/include" --include_path="/home/gabriel/LNLS/DRS/Firmware/C28/F28M36x_headers/include" -g --diag_warning=225 --display_error_number --issue_remarks --diag_wrap=off --preproc_with_compile --preproc_dependency="source/F28M36x_Gpio.d" --obj_directory="source" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: $<'
	@echo ' '

source/F28M36x_Mcbsp.obj: /home/gabriel/LNLS/DRS/Firmware/C28/F28M36x_common/source/F28M36x_Mcbsp.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C2000 Compiler'
	"/home/gabriel/ti/ccsv6/tools/compiler/ti-cgt-c2000_15.12.1.LTS/bin/cl2000" -v28 -ml -mt --float_support=fpu32 --vcu_support=vcu0 -O2 --opt_for_speed=1 --include_path="/home/gabriel/LNLS/DRS/Firmware/C28/F28M36x_ELP_DRS" --include_path="/home/gabriel/LNLS/DRS/Firmware/C28/F28M36x_ELP_DRS/DP_framework" --include_path="/home/gabriel/LNLS/DRS/Firmware/C28/F28M36x_ELP_DRS/DP_framework/ELP_DCL" --include_path="/home/gabriel/LNLS/DRS/Firmware/C28/F28M36x_ELP_DRS/DP_framework/SigGen" --include_path="/home/gabriel/LNLS/DRS/Firmware/C28/F28M36x_ELP_DRS/DP_framework/TimeSlicer" --include_path="/home/gabriel/LNLS/DRS/Firmware/C28/F28M36x_ELP_DRS/DP_framework/TI_DCL" --include_path="/home/gabriel/LNLS/DRS/Firmware/C28/F28M36x_ELP_DRS/HRADC_board" --include_path="/home/gabriel/LNLS/DRS/Firmware/C28/F28M36x_ELP_DRS/IPC_modules" --include_path="/home/gabriel/LNLS/DRS/Firmware/C28/F28M36x_ELP_DRS/PS_modules" --include_path="/home/gabriel/LNLS/DRS/Firmware/C28/F28M36x_ELP_DRS/PWM_modules" --include_path="/home/gabriel/ti/ccsv6/tools/compiler/ti-cgt-c2000_15.12.1.LTS/include" --include_path="/home/gabriel/LNLS/DRS/Firmware/C28/F28M36x_common/include" --include_path="/home/gabriel/LNLS/DRS/Firmware/C28/F28M36x_headers/include" -g --diag_warning=225 --display_error_number --issue_remarks --diag_wrap=off --preproc_with_compile --preproc_dependency="source/F28M36x_Mcbsp.d" --obj_directory="source" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: $<'
	@echo ' '

source/F28M36x_PieCtrl.obj: /home/gabriel/LNLS/DRS/Firmware/C28/F28M36x_common/source/F28M36x_PieCtrl.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C2000 Compiler'
	"/home/gabriel/ti/ccsv6/tools/compiler/ti-cgt-c2000_15.12.1.LTS/bin/cl2000" -v28 -ml -mt --float_support=fpu32 --vcu_support=vcu0 -O2 --opt_for_speed=1 --include_path="/home/gabriel/LNLS/DRS/Firmware/C28/F28M36x_ELP_DRS" --include_path="/home/gabriel/LNLS/DRS/Firmware/C28/F28M36x_ELP_DRS/DP_framework" --include_path="/home/gabriel/LNLS/DRS/Firmware/C28/F28M36x_ELP_DRS/DP_framework/ELP_DCL" --include_path="/home/gabriel/LNLS/DRS/Firmware/C28/F28M36x_ELP_DRS/DP_framework/SigGen" --include_path="/home/gabriel/LNLS/DRS/Firmware/C28/F28M36x_ELP_DRS/DP_framework/TimeSlicer" --include_path="/home/gabriel/LNLS/DRS/Firmware/C28/F28M36x_ELP_DRS/DP_framework/TI_DCL" --include_path="/home/gabriel/LNLS/DRS/Firmware/C28/F28M36x_ELP_DRS/HRADC_board" --include_path="/home/gabriel/LNLS/DRS/Firmware/C28/F28M36x_ELP_DRS/IPC_modules" --include_path="/home/gabriel/LNLS/DRS/Firmware/C28/F28M36x_ELP_DRS/PS_modules" --include_path="/home/gabriel/LNLS/DRS/Firmware/C28/F28M36x_ELP_DRS/PWM_modules" --include_path="/home/gabriel/ti/ccsv6/tools/compiler/ti-cgt-c2000_15.12.1.LTS/include" --include_path="/home/gabriel/LNLS/DRS/Firmware/C28/F28M36x_common/include" --include_path="/home/gabriel/LNLS/DRS/Firmware/C28/F28M36x_headers/include" -g --diag_warning=225 --display_error_number --issue_remarks --diag_wrap=off --preproc_with_compile --preproc_dependency="source/F28M36x_PieCtrl.d" --obj_directory="source" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: $<'
	@echo ' '

source/F28M36x_PieVect.obj: /home/gabriel/LNLS/DRS/Firmware/C28/F28M36x_common/source/F28M36x_PieVect.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C2000 Compiler'
	"/home/gabriel/ti/ccsv6/tools/compiler/ti-cgt-c2000_15.12.1.LTS/bin/cl2000" -v28 -ml -mt --float_support=fpu32 --vcu_support=vcu0 -O2 --opt_for_speed=1 --include_path="/home/gabriel/LNLS/DRS/Firmware/C28/F28M36x_ELP_DRS" --include_path="/home/gabriel/LNLS/DRS/Firmware/C28/F28M36x_ELP_DRS/DP_framework" --include_path="/home/gabriel/LNLS/DRS/Firmware/C28/F28M36x_ELP_DRS/DP_framework/ELP_DCL" --include_path="/home/gabriel/LNLS/DRS/Firmware/C28/F28M36x_ELP_DRS/DP_framework/SigGen" --include_path="/home/gabriel/LNLS/DRS/Firmware/C28/F28M36x_ELP_DRS/DP_framework/TimeSlicer" --include_path="/home/gabriel/LNLS/DRS/Firmware/C28/F28M36x_ELP_DRS/DP_framework/TI_DCL" --include_path="/home/gabriel/LNLS/DRS/Firmware/C28/F28M36x_ELP_DRS/HRADC_board" --include_path="/home/gabriel/LNLS/DRS/Firmware/C28/F28M36x_ELP_DRS/IPC_modules" --include_path="/home/gabriel/LNLS/DRS/Firmware/C28/F28M36x_ELP_DRS/PS_modules" --include_path="/home/gabriel/LNLS/DRS/Firmware/C28/F28M36x_ELP_DRS/PWM_modules" --include_path="/home/gabriel/ti/ccsv6/tools/compiler/ti-cgt-c2000_15.12.1.LTS/include" --include_path="/home/gabriel/LNLS/DRS/Firmware/C28/F28M36x_common/include" --include_path="/home/gabriel/LNLS/DRS/Firmware/C28/F28M36x_headers/include" -g --diag_warning=225 --display_error_number --issue_remarks --diag_wrap=off --preproc_with_compile --preproc_dependency="source/F28M36x_PieVect.d" --obj_directory="source" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: $<'
	@echo ' '

source/F28M36x_Sci.obj: /home/gabriel/LNLS/DRS/Firmware/C28/F28M36x_common/source/F28M36x_Sci.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C2000 Compiler'
	"/home/gabriel/ti/ccsv6/tools/compiler/ti-cgt-c2000_15.12.1.LTS/bin/cl2000" -v28 -ml -mt --float_support=fpu32 --vcu_support=vcu0 -O2 --opt_for_speed=1 --include_path="/home/gabriel/LNLS/DRS/Firmware/C28/F28M36x_ELP_DRS" --include_path="/home/gabriel/LNLS/DRS/Firmware/C28/F28M36x_ELP_DRS/DP_framework" --include_path="/home/gabriel/LNLS/DRS/Firmware/C28/F28M36x_ELP_DRS/DP_framework/ELP_DCL" --include_path="/home/gabriel/LNLS/DRS/Firmware/C28/F28M36x_ELP_DRS/DP_framework/SigGen" --include_path="/home/gabriel/LNLS/DRS/Firmware/C28/F28M36x_ELP_DRS/DP_framework/TimeSlicer" --include_path="/home/gabriel/LNLS/DRS/Firmware/C28/F28M36x_ELP_DRS/DP_framework/TI_DCL" --include_path="/home/gabriel/LNLS/DRS/Firmware/C28/F28M36x_ELP_DRS/HRADC_board" --include_path="/home/gabriel/LNLS/DRS/Firmware/C28/F28M36x_ELP_DRS/IPC_modules" --include_path="/home/gabriel/LNLS/DRS/Firmware/C28/F28M36x_ELP_DRS/PS_modules" --include_path="/home/gabriel/LNLS/DRS/Firmware/C28/F28M36x_ELP_DRS/PWM_modules" --include_path="/home/gabriel/ti/ccsv6/tools/compiler/ti-cgt-c2000_15.12.1.LTS/include" --include_path="/home/gabriel/LNLS/DRS/Firmware/C28/F28M36x_common/include" --include_path="/home/gabriel/LNLS/DRS/Firmware/C28/F28M36x_headers/include" -g --diag_warning=225 --display_error_number --issue_remarks --diag_wrap=off --preproc_with_compile --preproc_dependency="source/F28M36x_Sci.d" --obj_directory="source" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: $<'
	@echo ' '

source/F28M36x_Spi.obj: /home/gabriel/LNLS/DRS/Firmware/C28/F28M36x_common/source/F28M36x_Spi.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C2000 Compiler'
	"/home/gabriel/ti/ccsv6/tools/compiler/ti-cgt-c2000_15.12.1.LTS/bin/cl2000" -v28 -ml -mt --float_support=fpu32 --vcu_support=vcu0 -O2 --opt_for_speed=1 --include_path="/home/gabriel/LNLS/DRS/Firmware/C28/F28M36x_ELP_DRS" --include_path="/home/gabriel/LNLS/DRS/Firmware/C28/F28M36x_ELP_DRS/DP_framework" --include_path="/home/gabriel/LNLS/DRS/Firmware/C28/F28M36x_ELP_DRS/DP_framework/ELP_DCL" --include_path="/home/gabriel/LNLS/DRS/Firmware/C28/F28M36x_ELP_DRS/DP_framework/SigGen" --include_path="/home/gabriel/LNLS/DRS/Firmware/C28/F28M36x_ELP_DRS/DP_framework/TimeSlicer" --include_path="/home/gabriel/LNLS/DRS/Firmware/C28/F28M36x_ELP_DRS/DP_framework/TI_DCL" --include_path="/home/gabriel/LNLS/DRS/Firmware/C28/F28M36x_ELP_DRS/HRADC_board" --include_path="/home/gabriel/LNLS/DRS/Firmware/C28/F28M36x_ELP_DRS/IPC_modules" --include_path="/home/gabriel/LNLS/DRS/Firmware/C28/F28M36x_ELP_DRS/PS_modules" --include_path="/home/gabriel/LNLS/DRS/Firmware/C28/F28M36x_ELP_DRS/PWM_modules" --include_path="/home/gabriel/ti/ccsv6/tools/compiler/ti-cgt-c2000_15.12.1.LTS/include" --include_path="/home/gabriel/LNLS/DRS/Firmware/C28/F28M36x_common/include" --include_path="/home/gabriel/LNLS/DRS/Firmware/C28/F28M36x_headers/include" -g --diag_warning=225 --display_error_number --issue_remarks --diag_wrap=off --preproc_with_compile --preproc_dependency="source/F28M36x_Spi.d" --obj_directory="source" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: $<'
	@echo ' '

source/F28M36x_SysCtrl.obj: /home/gabriel/LNLS/DRS/Firmware/C28/F28M36x_common/source/F28M36x_SysCtrl.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C2000 Compiler'
	"/home/gabriel/ti/ccsv6/tools/compiler/ti-cgt-c2000_15.12.1.LTS/bin/cl2000" -v28 -ml -mt --float_support=fpu32 --vcu_support=vcu0 -O2 --opt_for_speed=1 --include_path="/home/gabriel/LNLS/DRS/Firmware/C28/F28M36x_ELP_DRS" --include_path="/home/gabriel/LNLS/DRS/Firmware/C28/F28M36x_ELP_DRS/DP_framework" --include_path="/home/gabriel/LNLS/DRS/Firmware/C28/F28M36x_ELP_DRS/DP_framework/ELP_DCL" --include_path="/home/gabriel/LNLS/DRS/Firmware/C28/F28M36x_ELP_DRS/DP_framework/SigGen" --include_path="/home/gabriel/LNLS/DRS/Firmware/C28/F28M36x_ELP_DRS/DP_framework/TimeSlicer" --include_path="/home/gabriel/LNLS/DRS/Firmware/C28/F28M36x_ELP_DRS/DP_framework/TI_DCL" --include_path="/home/gabriel/LNLS/DRS/Firmware/C28/F28M36x_ELP_DRS/HRADC_board" --include_path="/home/gabriel/LNLS/DRS/Firmware/C28/F28M36x_ELP_DRS/IPC_modules" --include_path="/home/gabriel/LNLS/DRS/Firmware/C28/F28M36x_ELP_DRS/PS_modules" --include_path="/home/gabriel/LNLS/DRS/Firmware/C28/F28M36x_ELP_DRS/PWM_modules" --include_path="/home/gabriel/ti/ccsv6/tools/compiler/ti-cgt-c2000_15.12.1.LTS/include" --include_path="/home/gabriel/LNLS/DRS/Firmware/C28/F28M36x_common/include" --include_path="/home/gabriel/LNLS/DRS/Firmware/C28/F28M36x_headers/include" -g --diag_warning=225 --display_error_number --issue_remarks --diag_wrap=off --preproc_with_compile --preproc_dependency="source/F28M36x_SysCtrl.d" --obj_directory="source" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: $<'
	@echo ' '

source/F28M36x_TempSensorConv.obj: /home/gabriel/LNLS/DRS/Firmware/C28/F28M36x_common/source/F28M36x_TempSensorConv.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C2000 Compiler'
	"/home/gabriel/ti/ccsv6/tools/compiler/ti-cgt-c2000_15.12.1.LTS/bin/cl2000" -v28 -ml -mt --float_support=fpu32 --vcu_support=vcu0 -O2 --opt_for_speed=1 --include_path="/home/gabriel/LNLS/DRS/Firmware/C28/F28M36x_ELP_DRS" --include_path="/home/gabriel/LNLS/DRS/Firmware/C28/F28M36x_ELP_DRS/DP_framework" --include_path="/home/gabriel/LNLS/DRS/Firmware/C28/F28M36x_ELP_DRS/DP_framework/ELP_DCL" --include_path="/home/gabriel/LNLS/DRS/Firmware/C28/F28M36x_ELP_DRS/DP_framework/SigGen" --include_path="/home/gabriel/LNLS/DRS/Firmware/C28/F28M36x_ELP_DRS/DP_framework/TimeSlicer" --include_path="/home/gabriel/LNLS/DRS/Firmware/C28/F28M36x_ELP_DRS/DP_framework/TI_DCL" --include_path="/home/gabriel/LNLS/DRS/Firmware/C28/F28M36x_ELP_DRS/HRADC_board" --include_path="/home/gabriel/LNLS/DRS/Firmware/C28/F28M36x_ELP_DRS/IPC_modules" --include_path="/home/gabriel/LNLS/DRS/Firmware/C28/F28M36x_ELP_DRS/PS_modules" --include_path="/home/gabriel/LNLS/DRS/Firmware/C28/F28M36x_ELP_DRS/PWM_modules" --include_path="/home/gabriel/ti/ccsv6/tools/compiler/ti-cgt-c2000_15.12.1.LTS/include" --include_path="/home/gabriel/LNLS/DRS/Firmware/C28/F28M36x_common/include" --include_path="/home/gabriel/LNLS/DRS/Firmware/C28/F28M36x_headers/include" -g --diag_warning=225 --display_error_number --issue_remarks --diag_wrap=off --preproc_with_compile --preproc_dependency="source/F28M36x_TempSensorConv.d" --obj_directory="source" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: $<'
	@echo ' '

source/F28M36x_usDelay.obj: /home/gabriel/LNLS/DRS/Firmware/C28/F28M36x_common/source/F28M36x_usDelay.asm $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: C2000 Compiler'
	"/home/gabriel/ti/ccsv6/tools/compiler/ti-cgt-c2000_15.12.1.LTS/bin/cl2000" -v28 -ml -mt --float_support=fpu32 --vcu_support=vcu0 -O2 --opt_for_speed=1 --include_path="/home/gabriel/LNLS/DRS/Firmware/C28/F28M36x_ELP_DRS" --include_path="/home/gabriel/LNLS/DRS/Firmware/C28/F28M36x_ELP_DRS/DP_framework" --include_path="/home/gabriel/LNLS/DRS/Firmware/C28/F28M36x_ELP_DRS/DP_framework/ELP_DCL" --include_path="/home/gabriel/LNLS/DRS/Firmware/C28/F28M36x_ELP_DRS/DP_framework/SigGen" --include_path="/home/gabriel/LNLS/DRS/Firmware/C28/F28M36x_ELP_DRS/DP_framework/TimeSlicer" --include_path="/home/gabriel/LNLS/DRS/Firmware/C28/F28M36x_ELP_DRS/DP_framework/TI_DCL" --include_path="/home/gabriel/LNLS/DRS/Firmware/C28/F28M36x_ELP_DRS/HRADC_board" --include_path="/home/gabriel/LNLS/DRS/Firmware/C28/F28M36x_ELP_DRS/IPC_modules" --include_path="/home/gabriel/LNLS/DRS/Firmware/C28/F28M36x_ELP_DRS/PS_modules" --include_path="/home/gabriel/LNLS/DRS/Firmware/C28/F28M36x_ELP_DRS/PWM_modules" --include_path="/home/gabriel/ti/ccsv6/tools/compiler/ti-cgt-c2000_15.12.1.LTS/include" --include_path="/home/gabriel/LNLS/DRS/Firmware/C28/F28M36x_common/include" --include_path="/home/gabriel/LNLS/DRS/Firmware/C28/F28M36x_headers/include" -g --diag_warning=225 --display_error_number --issue_remarks --diag_wrap=off --preproc_with_compile --preproc_dependency="source/F28M36x_usDelay.d" --obj_directory="source" $(GEN_OPTS__FLAG) "$(shell echo $<)"
	@echo 'Finished building: $<'
	@echo ' '


